name: printer_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0 # выше 3.6 некрасиво форматирует код
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  go_router: ^15.1.2
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  photo_manager: ^3.6.4 # display images
  webview_flutter: ^4.11.0
  file_picker: ^10.1.9
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  libre_doc_converter: ^0.1.1 # convert doc to pdf
  # vip
  purchases_flutter: ^8.7.4
  purchases_ui_flutter: ^8.7.4
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/printables/
  fonts:
    - family: inter400
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: inter500
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: inter600
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: inter700
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
