class PrinterModel {
  PrinterModel({
    required this.brand,
    required this.model,
  });

  final String brand;
  final String model;
}

List<PrinterModel> printerModel = [
  PrinterModel(brand: "HP", model: "OfficeJet Pro 9018e"),
  PrinterModel(brand: "Canon", model: "PIXMA TR4520"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-2850"),
  PrinterModel(brand: "Brother", model: "HL-L2350DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M283fdw"),
  PrinterModel(brand: "Canon", model: "imageCLASS LBP6230dw"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-2950"),
  PrinterModel(brand: "Brother", model: "MFC-J995DW"),
  PrinterModel(brand: "HP", model: "DeskJet Plus 4155"),
  PrinterModel(brand: "Canon", model: "MAXIFY GX4020"),
  PrinterModel(brand: "Epson", model: "Expression Premium XP-6100"),
  PrinterModel(brand: "Brother", model: "DCP-L2550DW"),
  PrinterModel(brand: "HP", model: "Envy 6055e"),
  PrinterModel(brand: "Canon", model: "PIXMA MG3620"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-4800"),
  PrinterModel(brand: "Brother", model: "HL-L2395DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro M15w"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF267dw"),
  PrinterModel(brand: "Epson", model: "WorkForce Pro WF-4740"),
  PrinterModel(brand: "Brother", model: "MFC-L2710DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 8025e"),
  PrinterModel(brand: "Canon", model: "PIXMA TS3520"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-3760"),
  PrinterModel(brand: "Brother", model: "HL-L3290CDW"),
  PrinterModel(brand: "HP", model: "Neverstop 1202w"),
  PrinterModel(brand: "Canon", model: "MAXIFY MB2720"),
  PrinterModel(brand: "Epson", model: "Expression Photo XP-8600"),
  PrinterModel(brand: "Brother", model: "DCP-J785DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M227fdw"),
  PrinterModel(brand: "Canon", model: "PIXMA TR8620"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-2860"),
  PrinterModel(brand: "Brother", model: "MFC-J4335DW"),
  PrinterModel(brand: "HP", model: "DeskJet 3755"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF743Cdw"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-15000"),
  PrinterModel(brand: "Brother", model: "HL-L6200DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 9015"),
  PrinterModel(brand: "Canon", model: "PIXMA G7020"),
  PrinterModel(brand: "Epson", model: "WorkForce Pro WF-3820"),
  PrinterModel(brand: "Brother", model: "MFC-L8900CDW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro M404dn"),
  PrinterModel(brand: "Canon", model: "imageCLASS LBP612Cdw"),
  PrinterModel(brand: "Epson", model: "Expression ET-2750"),
  PrinterModel(brand: "Brother", model: "DCP-L5500DN"),
  PrinterModel(brand: "HP", model: "Envy Pro 6455"),
  PrinterModel(brand: "Canon", model: "MAXIFY GX7020"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-5800"),
  PrinterModel(brand: "Brother", model: "HL-L6400DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M130fw"),
  PrinterModel(brand: "Canon", model: "PIXMA TS8320"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-3850"),
  PrinterModel(brand: "Brother", model: "MFC-L6900DW"),
  PrinterModel(brand: "HP", model: "DeskJet 2700e"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF644Cdw"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-110"),
  PrinterModel(brand: "Brother", model: "HL-L2390DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 6978"),
  PrinterModel(brand: "Canon", model: "PIXMA TR7020"),
  PrinterModel(brand: "Epson", model: "Expression Premium XP-7100"),
  PrinterModel(brand: "Brother", model: "DCP-T720DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M232sdw"),
  PrinterModel(brand: "Canon", model: "MAXIFY MB5020"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-2803"),
  PrinterModel(brand: "Brother", model: "MFC-J6945DW"),
  PrinterModel(brand: "HP", model: "Envy 7855"),
  PrinterModel(brand: "Canon", model: "PIXMA G6020"),
  PrinterModel(brand: "Epson", model: "WorkForce Pro WF-4830"),
  PrinterModel(brand: "Brother", model: "HL-L8360CDW"),
  PrinterModel(brand: "HP", model: "Neverstop 1000w"),
  PrinterModel(brand: "Canon", model: "imageCLASS LBP162dw"),
  PrinterModel(brand: "Epson", model: "Expression ET-3750"),
  PrinterModel(brand: "Brother", model: "DCP-L3550CDW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M227sdn"),
  PrinterModel(brand: "Canon", model: "PIXMA TS9520"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-4850"),
  PrinterModel(brand: "Brother", model: "MFC-J5945DW"),
  PrinterModel(brand: "HP", model: "DeskJet 4155e"),
  PrinterModel(brand: "Canon", model: "MAXIFY GX3020"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-7710"),
  PrinterModel(brand: "Brother", model: "HL-L5200DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 7720"),
  PrinterModel(brand: "Canon", model: "PIXMA MG7120"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-16500"),
  PrinterModel(brand: "Brother", model: "MFC-L8905CDW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro M404n"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF445dw"),
  PrinterModel(brand: "Epson", model: "Expression Photo XP-15000"),
  PrinterModel(brand: "Brother", model: "DCP-T420W"),
  PrinterModel(brand: "HP", model: "Envy 6020e"),
  PrinterModel(brand: "Canon", model: "PIXMA TR4720"),
  PrinterModel(brand: "Epson", model: "WorkForce Pro WF-4720"),
  PrinterModel(brand: "Brother", model: "HL-L6400DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M148fdw"),
  PrinterModel(brand: "Canon", model: "MAXIFY MB2020"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-3800"),
  PrinterModel(brand: "Brother", model: "MFC-J5335DW"),
  PrinterModel(brand: "HP", model: "DeskJet 3752"),
  PrinterModel(brand: "Canon", model: "PIXMA TS6420"),
  PrinterModel(brand: "Epson", model: "Expression ET-4700"),
  PrinterModel(brand: "Brother", model: "DCP-L5650DN"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 8035e"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF455dw"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-4734"),
  PrinterModel(brand: "Brother", model: "HL-L3270CDW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro M15a"),
  PrinterModel(brand: "Canon", model: "PIXMA G7020"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-4850"),
  PrinterModel(brand: "Brother", model: "MFC-J4535DW"),
  PrinterModel(brand: "HP", model: "Envy Pro 6452"),
  PrinterModel(brand: "Canon", model: "MAXIFY MB5120"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-2955"),
  PrinterModel(brand: "Brother", model: "HL-L2395DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M232dw"),
  PrinterModel(brand: "Canon", model: "PIXMA TR4520"),
  PrinterModel(brand: "Epson", model: "Expression ET-2700"),
  PrinterModel(brand: "Brother", model: "DCP-J552DW"),
  PrinterModel(brand: "HP", model: "DeskJet 4158"),
  PrinterModel(brand: "Canon", model: "imageCLASS LBP612Cdw"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-2800"),
  PrinterModel(brand: "Brother", model: "MFC-L6905DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 8210"),
  PrinterModel(brand: "Canon", model: "PIXMA TS8320"),
  PrinterModel(brand: "Epson", model: "WorkForce Pro WF-4740"),
  PrinterModel(brand: "Brother", model: "HL-L5200DN"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M130fn"),
  PrinterModel(brand: "Canon", model: "MAXIFY GX4020"),
  PrinterModel(brand: "Epson", model: "Expression XP-440"),
  PrinterModel(brand: "Brother", model: "DCP-T820DW"),
  PrinterModel(brand: "HP", model: "Envy 5055"),
  PrinterModel(brand: "Canon", model: "PIXMA MG6320"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-4850"),
  PrinterModel(brand: "Brother", model: "MFC-J6545DW"),
  PrinterModel(brand: "HP", model: "Neverstop 1200w"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF735Cdw"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-2850"),
  PrinterModel(brand: "Brother", model: "HL-L3270CDW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro MFP M227fdn"),
  PrinterModel(brand: "Canon", model: "PIXMA TR8620"),
  PrinterModel(brand: "Epson", model: "Expression ET-3700"),
  PrinterModel(brand: "Brother", model: "DCP-L5500DN"),
  PrinterModel(brand: "HP", model: "DeskJet 2734"),
  PrinterModel(brand: "Canon", model: "MAXIFY MB2720"),
  PrinterModel(brand: "Epson", model: "EcoTank ET-16650"),
  PrinterModel(brand: "Brother", model: "MFC-J6940DW"),
  PrinterModel(brand: "HP", model: "OfficeJet Pro 6968"),
  PrinterModel(brand: "Canon", model: "PIXMA TS5320"),
  PrinterModel(brand: "Epson", model: "WorkForce WF-2865"),
  PrinterModel(brand: "Brother", model: "HL-L2390DW"),
  PrinterModel(brand: "HP", model: "LaserJet Pro M15w"),
  PrinterModel(brand: "Canon", model: "imageCLASS MF267dw"),
  PrinterModel(brand: "Epson", model: "Expression Photo XP-8600"),
  PrinterModel(brand: "Brother", model: "DCP-J785DW"),
];
